name: Slack workflow run notification reusable

on:
  workflow_call:
  workflow_run:
    workflows: ["*"]
    types:
      - requested
      - completed

jobs:                                                                                                                                                                                                                                                                          
   notify:                                                                                                                                                                                                                                                                      
     uses: rasodu/github-reusable-workflows/.github/workflows/notifications.yml@master